name: CI/CD workflow for Maven Build and Sonar Code scan

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build and SonarQube Scan with Maven
        run: |
          mvn clean install sonar:sonar \
            -Dsonar.projectKey=my-Java-web-app \
            -Dsonar.organization=my-org \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
